### ISSUE TITLE
Unpin required cirq version

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#1708]
Ideally, we'd support any Cirq version >=1.4 <2.0 (i.e. ~=1.4). The breaking change in https://github.com/quantumlib/Cirq/pull/6960 complicates this

**Comment by mpharrigan** [comment]
we could use `cirq.OP_TREE` which exists in all versions

**Comment by mpharrigan** [comment]
mypy is confusing me with cirq 1.5.0. An example error:

```
qualtran/bloqs/swap_network/cswap_approx.py:75: error: Missing return statement  [return]
qualtran/bloqs/swap_network/cswap_approx.py:82: error: Argument 1 to "list" has incompatible type "Operation | Iterable[OP_TREE]"; expected "Iterable[Operation | Iterable[OP_TREE]]"  [arg-type]
qualtran/bloqs/swap_network/cswap_approx.py:83: error: Argument 1 to "list" has incompatible type "Operation | Iterable[OP_TREE]"; expected "Iterable[Operation | Iterable[OP_TREE]]"  [arg-type]
```

this worked with `OpTree` but fails with `OP_TREE` even though `OP_TREE` is supposed to include `Iterable[OP_TREE]` as part of the union

**Comment by pavoljuhas** [comment]
The mypy should be fixed by #1724.
With respect to the failure in test_add_decomposition I see it as well, for example with
```
pytest --pyargs "qualtran.bloqs.arithmetic.addition_test::test_add_decomposition[0-0-3]"
```
I have bisected that failure to https://github.com/quantumlib/Cirq/pull/7537, specifically the addition of [if-has_unitary-return-unitary block](https://github.com/quantumlib/Cirq/pull/7537/files#diff-c19df60bbf6e2c946bf5dd45816727fcbe0f73b696632f8afd474994e3394772L189) to `cirq.kraus`.  The problem is that the `circuit0` created in the test reports True for `cirq.has_unitary(circuit0)`, but throws TypeError for `cirq.unitary(circuit0)` after line 79 here -

https://github.com/quantumlib/Qualtran/blob/44f95f0927157e1abee38ec2d0f4ba455938882a/qualtran/bloqs/arithmetic/addition_test.py#L70-L79

The exception is the same with Cirq-1.4.0.  Here is a patch to trigger it before any calls to simulator:
```patch
diff --git a/qualtran/bloqs/arithmetic/addition_test.py b/qualtran/bloqs/arithmetic/addition_test.py
index 3856f7db..94ebe2f6 100644
--- a/qualtran/bloqs/arithmetic/addition_test.py
+++ b/qualtran/bloqs/arithmetic/addition_test.py
@@ -79,2 +79,7 @@ def test_add_decomposition(a: int, b: int, num_bits: int):
     circuit0 = cirq.Circuit(op)
+
+    if cirq.has_unitary(circuit0):
+        cirq.unitary(circuit0)
+    return
+
     ancillas = sorted(circuit.all_qubits())[-num_anc:]

```

The `has_unitary` inconsistency happens also for `op.gate` which gives True for cirq_unitary; the `op` was created from `gate` on line 75, but that `gate` gives False for `has_unitary(gate)`.

@mpharrigan - can you check the code for `op.gate._has_unitary_`?
This test error should resolve if its `_has_unitary_` gave False as the originating `gate`.

**Comment by pavoljuhas** [comment]
> It's not a surprise that this was a bug on our side :)

I _am_ surprised, we have enough bugs to share on our own.  :)
